import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { authOptions } from './pages/api/auth/[...nextauth]'
import SessionProvider from './sessionProvider'
import Login from './components/login'
import Home from './page'
import { getServerSession } from 'next-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Medication Tracker',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <Home/>
          )}
          
        </SessionProvider>
      </body>
    </html>
  )
}
